version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key
      - CORS_ORIGIN=http://44.204.30.85:3005,http://localhost:3000
    networks:
      - taskflow-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://44.204.30.85:5000
    container_name: frontend
    ports:
      - "3005:3000"
    environment:
      - REACT_APP_API_URL=http://44.204.30.85:5000
    networks:
      - taskflow-net
    depends_on:
      - backend

networks:
  taskflow-net:
    driver: bridge
